<?php
/**
 * @var \ntesic\generator\generator\crud\Builder $builder
 */
echo "<?php\n"
?>
/**
* @var \Phalcon\Mvc\View $this
* @var \ntesic\boilerplate\data\QueryDataProvider $dataProvider
* @var string $script_foot
*/

use \ntesic\Helpers\Tag;
$inlineJs = "var gridViewKey = '" . $this->router->getControllerName() . "';";
$inlineJs .="var currentUrl = '" . $this->router->getModuleName() . "/" . $this->router->getControllerName() ."';";
$this->assets->addInlineJs($inlineJs);

$deleteMenu = new \Ajax\bootstrap\html\content\HtmlDropdownItem('delete');
$deleteMenu->setCaption('<i class="fa fa-trash">&nbsp;</i>Delete')->onClick('deleteMultiple();');
$dropdownMenu = $this->jquery->bootstrap()->htmlDropdown('actions', '<span class="glyphicon glyphicon-flash"></span> Selected', [$deleteMenu,], 'btn-default');
$selectedMenu = $this->jquery->bootstrap()->htmlButtongroups('btn-group');
$selectedMenu->addElement($dropdownMenu);
$selectedMenu->compile($this->jquery);

echo \ntesic\boilerplate\grid\KartikGridView::widget([
    'columns' => [
        <?= $builder->getGridViewAttributes() ?>
        [
            'class' => '\ntesic\boilerplate\grid\CheckboxColumn',
        ],
        [
            'class' => '\ntesic\boilerplate\grid\ActionColumn',
        ],
    ],
    'dataProvider' => $dataProvider,
    'options' => [
        'id' => $this->router->getControllerName() . '-grid'
    ],
    'toolbar' => [
        [
            'content' => $selectedMenu,
        ],
    ],
    'panel' => [
        'heading' => "<h3 class=\"panel-title\"><i class=\"glyphicon glyphicon-list\"></i>  " . '<?=\ntesic\boilerplate\Helpers\Text::pluralize(\ntesic\boilerplate\Helpers\Text::camel2words($builder->getClassName($builder->getModelClass()))) ?>' . "</h3>",
        'type' => 'default',
        'before' => Tag::linkTo([
            'action' => $this->url->get('create', null, null, $this->router->getModuleName() . '/' . $this->router->getControllerName() . '/'),
            'text' => '<span class="glyphicon glyphicon-plus"></span> New',
            'class' => 'btn btn-success',
        ]),
    ],
]);

?>

