<?php
/**
 * Copyright (c) 2016.
 * @author Nikola Tesic (nikolatesic@gmail.com)
 */

/**
 * Created by PhpStorm.
 * User: Nikola
 * Date: 12/29/2016
 * Time: 11:20 AM
 */
/**
 * @var \ntesic\generator\generator\crud\Builder $builder
 */
echo "<?php\n";
?>
namespace <?=$builder->getNamespace($builder->getFormClass()) ?>;

use \ntesic\boilerplate\Form\Form as BaseForm;

class <?=$builder->getClassName($builder->getFormClass()) ?> extends BaseForm
{

    public function initialize()
    {
        parent::initialize();
        $csrf = new \Phalcon\Forms\Element\Hidden($this->security->getTokenKey(), ['value' => $this->security->getToken()]);
        $this->add($csrf);
<?php
foreach ($builder->getDataTypes() as $column) {
    echo $builder->generateFormElement($column);
}
?>
    }
}