<?php
/**
 * Copyright (c) 2016.
 * @author Nikola Tesic (nikolatesic@gmail.com)
 */

/**
 * Created by PhpStorm.
 * User: Nikola
 * Date: 12/30/2016
 * Time: 5:47 PM
 */
/**
 * @var \ntesic\generator\generator\model\Builder $builder
 */
echo "<?php\n";
?>

namespace App\Models;

use App\Models\Base\<?=$builder->getClassName($builder->getModelClass()) ?> as BaseModel;

class <?=$builder->getClassName($builder->getModelClass()) ?> extends BaseModel
{

}
